### ISSUE TITLE
will it work in Windows?

### ISSUE THREAD

**Issue by Sandy4321** [fracpete/tclass-weka-package#1]
will it work in Windows?

**Comment by fracpete** [comment]
It's written in Java and, from memory, doesn't contain any native libraries. I'd say yes.

**Comment by Sandy4321** [comment]
By the way, there is mentioning 
Interpretable Classification Rule Mining Algorithm

only code example from
https://waikato.github.io/weka-wiki/packages/unofficial/

But link to this
Interpretable Classification Rule Mining Algorithm
Is broken
Does it mean that there no such algorithm in weka?
Or to whom ask ask if there is such algorithm in weka
How to find who maintains weka?

**Comment by fracpete** [comment]
Unofficial packages are not maintained by the University of Waikato. If external authors take down their websites, there is nothing we can do about. For questions re Weka and it's official packages, use the Weka mailing list. See the the official Weka homepage for details or the Weka wiki.
