### ISSUE TITLE
will it work for mixed continues and categorical time series?

### ISSUE THREAD

**Issue by Sandy4321** [fracpete/tclass-weka-package#2]
will it work for mixed continues and categorical time series?

**Comment by fracpete** [comment]
Not sure. I'm not the author of the library, I only turned it into a Weka package. Also never used it. Just give it a go.

**Comment by Sandy4321** [comment]
I see so how to find  author?

**Comment by fracpete** [comment]
It's mentioned in the readme: Waleed Kadous.
